# Generated by Django 4.1.7 on 2023-04-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to="blogs.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to="blogs.comment",
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="postaudio",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_audios",
                to="blogs.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_images",
                to="blogs.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="blogs.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="postmark",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_marks",
                to="blogs.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="postvideo",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_videos",
                to="blogs.post",
                verbose_name="Post",
            ),
        ),
    ]
